INSERT INTO `utility_operators` (`type`, `state`, `code`, `name`, `category`, `label`, `icon`, `is_active`, `created_at`, `updated_at`) VALUES
('ElectriCityap', '1', 'APEP', 'APEPDCL - Andhra Pradesh', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityap', '1', 'APSP', 'APSPDCL - Andhra Pradesh', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityas', '2', 'APDC', 'APDCL (Non-RAPDR) - ASSAM', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityas', '2', 'APDR', 'APDCL (RAPDR) - ASSAM', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitybr', '3', 'NBBR', 'North Bihar Power Distribution Co. Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitybr', '3', 'SBBR', 'South Bihar Power Distribution Co. Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitych', '25', 'CSPD', 'Chhattisgarh State Power Distribution Company Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitydh', '5', 'BSRD', 'BSES Rajdhani Power Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitydh', '5', 'BSYD', 'BSES Yamuna Power Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitydh', '5', 'NDMC', 'New Delhi Municipal Council (NDMC)', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitydh', '5', 'TAPD', 'Tata Power Delhi Distribution Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygo', '26', 'GOED', 'Goa Electricity Department', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'DGVC', 'Dakshin Gujarat Vij Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'MGVG', 'Madhya Gujarat Vij Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'PGVG', 'Paschim Gujarat Vij Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'TPAH', 'Torrent Power Limited - Ahmedabad', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'TPBW', 'Torrent Power Limited - Bhiwandi', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'TPSR', 'Torrent Power Limited - Surat', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitygu', '6', 'UGVG', 'Uttar Gujarat Vij Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityhr', '7', 'DHBH', 'Dakshin Haryana Bijli Vitran Nigam', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityhr', '7', 'UHBV', 'Uttar Haryana Bijli Vitran Nigam', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityhm', '8', 'HPSE', 'Himachal Pradesh State Electricity Board Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityjh', '24', 'JUSC', 'Jamshedpur Utilities & Services (JUSCO)', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityjh', '24', 'JBVN', 'Jharkhand Bijli Vitran Nigam Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityka', '10', 'BESC', 'Bangalore Electricity Supply Company Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityka', '10', 'CESK', 'CESCOM - KARNATAKA', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityka', '10', 'GESK', 'Gulbarga Electricity Supply Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityka', '10', 'HESK', 'Hubli Electricity Supply Company Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitykr', '11', 'KSEB', 'Kerala State Electricity Board Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymp', '14', 'MKMP', 'Madhya Kshetra Vitaran (Rural) - Madhya Pradesh', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymp', '14', 'MKVU', 'Madhya Kshetra Vitaran (Urban) - Madhya Pradesh', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymp', '14', 'PVMP', 'Paschim Kshetra Vidyut Vitaran - Madhya Pradesh', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymp', '14', 'PKVU', 'Poorv Kshetra Vitaran (NBG-Urban) - MADHYA PRADESH', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymp', '14', 'PKVR', 'Poorv Kshetra Vitaran (Rural) - MADHYA PRADESH', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymh', '13', 'ADEM', 'Adani Electricity', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymh', '13', 'BEUM', 'BEST Undertaking', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymh', '13', 'MSEM', 'MSEDCL', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymh', '13', 'TAPM', 'Tata Power - MUMBAI', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitymg', '21', 'MPDC', 'Meghalaya Power Dist Corp Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityor', '17', 'JKPD', 'Jammu and Kashmir Power Development Department', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityor', '17', 'NESO', 'NESCO Utility', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityor', '17', 'SOTO', 'Southern Electricity Supply Company Of Odisha Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityor', '17', 'TPCO', 'TP Central Odisha Distribution Limited (TPCODL)', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityor', '17', 'WESO', 'WESCO Utility', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitypn', '18', 'PSPC', 'Punjab State Power Corporation Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityra', '19', 'AVVR', 'Ajmer Vidyut Vitran Nigam Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityra', '19', 'JVVR', 'Jaipur Vidyut Vitran Nigam', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityra', '19', 'JDVR', 'Jodhpur Vidyut Vitran Nigam Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityra', '19', 'KEDR', 'Kota Electricity Distribution Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityra', '19', 'TPAR', 'Tata Power AJMER - RAJASTHAN', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitytn', '20', 'TNEB', 'Tamil Nadu Electricity Board', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityte', '28', 'TESS', 'Telangana Co-Operative Electric Supply Society Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityte', '28', 'TSSP', 'Telangana State Southern Power Distribution Company', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitytr', '30', 'TSTP', 'Tripura Electricity Corp Ltd', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityup', '21', 'KESC', 'Kanpur Electricity Supply Company', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityup', '21', 'TPAG', 'Torrent Power Limited - Agra', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityup', '21', 'URUP', 'Uttar Pradesh Power Corporation Ltd (RURAL)', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityup', '21', 'UUUP', 'Uttar Pradesh Power Corporation Ltd (Urban - Smart Meter)', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCityut', '29', 'UPUK', 'Uttarakhand Power Corporation Ltd - UPCL', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitywb', '23', 'CESC', 'Calcutta Electric Supply Corporation Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('ElectriCitywb', '23', 'WBSE', 'West Bengal State Electricity Distribution Company Limited', 'Electric', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AAVA', 'Aavas Financiers', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ADHF', 'Adani Housing Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ABDL', 'Aditya Birla Finance ltd. (ABFL)', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ABHF', 'Aditya Birla Housing Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AMIL', 'Agora Microfinance India Ltd - AMIL', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ACHF', 'Altum Credo Home Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AFPL', 'Annapurna Finance Private Limited-MSME', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AROH', 'Arohan Financial Services Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ASCA', 'Ascend Capital', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ASPI', 'Aspire Home Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AVAI', 'Avail', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'AFSL', 'Avanse Financial Services Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ABLM', 'Axis Bank Limited-Microfinance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BLFL', 'Baid Leasing and Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BAAF', 'Bajaj Auto Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BAJF', 'Bajaj Finserv', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BRFL', 'BERAR Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BFIL', 'Bharat Financial Inclusion Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CGCL', 'Capri Global Capital Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CGHF', 'Capri Global Housing Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CIFC', 'Chaitanya India Fin Credit Pvt Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CLIX', 'Clix', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CRWC', 'Credit Wise Capital', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CAGM', 'CreditAccess Grameen - Microfinance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'CAGR', 'CreditAccess Grameen - Retail Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'BBLR', 'DCB Bank Loan Repayment', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'DCAL', 'Digamber Capfin Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'DMIF', 'DMI Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'DKGF', 'Dvara Kshetriya Gramin Financials Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'EFPL', 'Eduvanz Financing Pvt. Ltd.', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ESSK', 'ESS KAY FINCORP', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'FAIR', 'Faircent', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'FSFB', 'Fincare Small Finance Bank', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'FIXL', 'FlexiLoans', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'FLEX', 'FlexSalary', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'HEFC', 'Hero FinCorp', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'HFSL', 'Hiranandani Financial Services Pvt  Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'HCIL', 'Home Credit India Finance Pvt. Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'HFFL', 'Home First Finance Company India Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'I2IF', 'I2I Funding', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ICIL', 'ICICI Bank Ltd - Loans', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'IDFL', 'IDFC First Bank Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'IIFL', 'IIFL Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'IIFH', 'IIFL Home Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'IHLL', 'India Home Loan Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ISFC', 'India Shelter Finance Corporation Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ICFL', 'Indiabulls Consumer Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'IBHF', 'INDIABULLS HOUSING FINANCE', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'INBC', 'INDUSIND BANK - CFD', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'JMFL', 'Jain Motor Finmart', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'JSFB', 'Jana Small Finance Bank', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'JFSP', 'Janakalyan Financial Services Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'JDFI', 'John Deere Financial India Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KNFL', 'Kanakadurga Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KHFP', 'Khush Housing Finance Pvt Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KINC', 'Kinara Capital', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KIST', 'Kissht', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KMBL', 'Kotak Mahindra Bank Ltd.-Loans', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'KMPL', 'Kotak Mahindra Prime Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'LTFL', 'L&T Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'LTHF', 'L&T Housing Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'LMPL', 'Light Microfinance Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'LTAP', 'LoanTAP', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'LOKS', 'LokSuvidha', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MFIL', 'Mahaveer Finance India Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MFSL', 'Mahindra and Mahindra Financial Services Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MRHF', 'Mahindra Rural Housing Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MFLV', 'Manappuram Finance Limited-Vehicle Loan', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MCIL', 'Maxvalue Credits And Investments Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MMIL', 'Midland Microfin Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MIFL', 'Mintifi Finserve Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MOHF', 'Motilal Oswal Home Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MUTF', 'Muthoot Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'MFLL', 'Muthoot Fincorp Ltd', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'NNAM', 'Nagar Nigam Aligarh- muncipality', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'NAFA', 'Netafim Agricultural Financing Agency Pvt. Ltd.', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'NIDF', 'Nidhilakshmi Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'NMFL', 'NM Finance', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'OHMY', 'OHMYLOAN', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'OHLP', 'OMLP2P.COM', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ORBR', 'Oroboro', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'PAIS', 'PaisaDukan', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'POFL', 'Pooja Finelease', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SAML', 'Samasta Microfinance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SHRI', 'SHRIRAM CITY UNION FINANCE LIMITED', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SHFL', 'Shriram Housing Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SMEC', 'SMEcorner', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SNAP', 'Snapmint', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'STSF', 'StashFin', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'SMPL', 'Svatantra Microfin Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'TCHF', 'Tata Capital Financial Services Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'TCHL', 'Tata Capital Housing Finance Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'TVSC', 'TVS Credit', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'USFB', 'Ujjivan Small Finance Bank', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'VART', 'Varthana', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'VFSP', 'Vistaar Financial services Private Limited', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Loan', 'Loan', 'ZESM', 'ZestMoney', 'Loan', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'AVTG', 'Aavantika Gas Ltd', 'Gas', 'Customer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'ASSG', 'Assam Gas Company Limited', 'Gas', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'BHAG', 'Bhagyanagar Gas Limited', 'Gas', 'CRN Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'CUGL', 'Central U.P. Gas Limited', 'Gas', 'Customer Code/CRN Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'CGSM', 'Charotar Gas Sahakari Mandali Ltd', 'Gas', 'Customer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'GAIG', 'GAIL Gas Limited', 'Gas', 'BP Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'GREG', 'Green Gas Limited(GGL)', 'Gas', 'CRN Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'GUJG', 'Gujarat Gas Limited', 'Gas', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'HARG', 'Haryana City Gas', 'Gas', 'CRN Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'INAG', 'Indian Oil-Adani Gas Private Limited', 'Gas', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'INPG', 'Indraprastha Gas Limited', 'Gas', 'Business Partner Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'IRMG', 'IRM Energy Private Limited', 'Gas', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'MAHG', 'Mahanagar Gas- Mumbai', 'Gas', 'CA Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'MEGG', 'Megha Gas', 'Gas', 'CRN NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'SABG', 'Sabarmati Gas Limited (SGL)', 'Gas', 'Consumer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'SWGL', 'Sanwariya Gas Limited', 'Gas', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'TGML', 'Torrent Gas Moradabad Limited', 'Gas', 'CRN NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'TRIG', 'Tripura Natural Gas', 'Gas', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Gas', 'Gas', 'UCPG', 'Unique Central Piped Gases Pvt Ltd (UCPGPL)', 'Gas', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('LPG', 'Gas', 'BHG', 'Bharat Gas', 'Gas', 'Registered Contact Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('LPG', 'Gas', 'HPG', 'HP Gas', 'Gas', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('LPG', 'Gas', 'ING', 'Indane Gas', 'Gas', 'Registered Contact Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'ABHI', 'Aditya Birla Health Insurance Co Limited', 'Insurance', 'POLICY NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'AELI', 'Aegon Life Insurance', 'Insurance', 'POLICY NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'AVLI', 'Aviva Life Insurance', 'Insurance', 'POLICY NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'BAGI', 'Bajaj Allianz General Insurance', 'Insurance', 'Policy Number (without hyphen)', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'BJLI', 'Bajaj Allianz Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'BALI', 'Bharti Axa Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'GHOI', 'Canara HSBC Oriental Bank of Commerce Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'DPLI', 'DHFL Pramerica Life Insurance Co. Ltd', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'ETLI', 'Edelweiss Tokio Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'EXLI', 'Exide Life Insurance', 'Insurance', 'POLICY NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'FGLI', 'Future Generali India Life Insurance Company Limited', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'HDLI', 'HDFC Life Insurance Co. Ltd.', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'IPLI', 'ICICI Prudential Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'IFLI', 'IDBI federal Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'INFI', 'INDIA FIRST Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'KTLI', 'Kotak Life Insurance Company Limited', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'LICI', 'Life Insurance Corporation of India', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'MHHI', 'Magma HDI - Health Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'MHLI', 'Magma HDI - Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'MHMI', 'Magma HDI - Motor Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'MBHI', 'Max Bupa Health Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'MXLI', 'Max Life Insurance', 'Insurance', 'POLICY NO', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'PNBM', 'PNB Metlife', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'PLLI', 'Pramerica Life Insurance Limited', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'RGLI', 'Reliance General Insurance Company Limited', 'Insurance', 'Previous Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'RNLI', 'Reliance Nippon Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'RSLI', 'Royal Sundaram General Insurance Co. Limited', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'SBLI', 'SBI Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'SBGI', 'SBIG', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'SGLI', 'Shriram General Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'SHLI', 'Shriram Life Insurance Co Ltd', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'ICHI', 'Star Union Dai Ichi Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'TALI', 'Tata AIA Life Insurance', 'Insurance', 'Policy Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Insurance', 'Insurance', 'VHLI', 'Vastu Housing Finance Corporation Limited', 'Insurance', 'Loan Account No', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'APBF', 'Airtel Payments Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'AUBF', 'AU Bank Fastag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'AXIF', 'Axis Bank', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'BOBF', 'Bank of Baroda', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'BOMF', 'Bank of Maharashtra', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'CABF', 'Canara Bank Fastag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'EQUF', 'Equitas FASTag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'FEBF', 'Federal Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'HDFF', 'HDFC Bank', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'ICIF', 'ICICI Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'IDBF', 'IDBI Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'IDFF', 'IDFC First Bank', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'INBF', 'Indian Bank Fastag', 'FASTag', 'Vehicle Registration Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'IHMF', 'Indian Highways Management Company', 'FASTag', 'Vehicle Registration Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'IIBF', 'IndusInd Bank', 'FASTag', 'Vehicle Registration Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'IOBF', 'IOB FASTag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'JKBF', 'Jammu and Kashmir Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'KABF', 'Karnataka Bank Fastag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'KMBF', 'Kotak Mahindra Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'LTIF', 'Livquik Technology India Private Limited', 'FASTag', 'Vehicle Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'PAUF', 'Paul Merchants', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'PTMF', 'Paytm Payments Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'SABF', 'Saraswat Bank FASTag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'SIBF', 'South Indian Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'SBIF', 'State Bank of India', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'TRAF', 'Transaction Analyst FASTag', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'TILF', 'Transcorp International Limited', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'UCOF', 'UCO Bank', 'FASTag', 'Vehicle Registered Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('FASTag', 'FASTag', 'UBIF', 'Union Bank of India', 'FASTag', 'Vehicle Registration Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'AMCW', 'Ahmedabad Municipal Corporation', 'Water', 'Citizen ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'BWSS', 'Bangalore Water Supply and Sewerage Board (BWSSB)', 'Water', 'RR. Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'BMCW', 'Bhopal Municipal Corporation', 'Water', 'Connection ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'DDAW', 'Delhi Development Authority (DDA)', 'Water', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'DLBW', 'Delhi Jal Board', 'Water', 'K Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'DPHE', 'Department of Public Health Engineering-Water, Mizoram', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'GWMC', 'Greater Warangal Municipal Corporation', 'Water', 'Connection ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'GMCW', 'Gwalior Municipal Corporation', 'Water', 'Connection ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'HUDA', 'Haryana Urban Development Authority', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'HMWS', 'Hyderabad Metropolitan Water Supply and Sewerage Board (HMWSSB)', 'Water', 'CAN Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'IMCW', 'Indore Municipal Corporation', 'Water', 'Service Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'JMCW', 'Jabalpur Municipal Corporation', 'Water', 'Service Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'JVNN', 'Jalkal Vibhag Nagar Nigam Prayagraj', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'KDMC', 'Kalyan Dombivali Municipal Corporation', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'KWAW', 'Kerala Water Authority (KWA)', 'Water', 'Connection ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MPUN', 'Madhya Pradesh Urban (e-Nagarpalika)', 'Water', 'ConnNo', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MUCC', 'Municipal Corporation Chandigarh', 'Water', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MCJW', 'Municipal Corporation Jalandhar', 'Water', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MCRL', 'Municipal Corporation Ludhiana', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MCAW', 'Municipal Corporation of Amritsar', 'Water', 'Account Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MCGW', 'Municipal Corporation of Gurugram (MCG)', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'MCCW', 'Mysuru City Corporation', 'Water', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'NNAW', 'Nagar Nigam Aligarh', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'NDMW', 'New Delhi Municipal Council (NDMC)', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'PHED', 'Public Health Engineering Department, Haryana', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'PNMW', 'Pune Municipal Corporation', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'PMCW', 'Punjab Municipal Corporation/Council', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'RMCW', 'Ranchi Municipal Corporation', 'Water', 'Consumer Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'SMCW', 'Silvassa Municipal Council', 'Water', 'Form Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'SUMC', 'Surat Municipal Corporation', 'Water', 'Connection Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'UNNW', 'Ujjain Nagar Nigam � PHED', 'Water', 'Mobile Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'UITW', 'Urban Improvement Trust (UIT) - Bhiwadi', 'Water', 'Customer ID', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('Water', 'Water', 'UKJS', 'Uttarakhand Jal Sansthan', 'Water', 'Computer Code', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bharat-billpay.png', 1, NOW(), NOW()),
('PostPaid', 'PostPaid', 'ATP', 'Airtel', 'Prepaid', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/airtel.png', 1, NOW(), NOW()),
('PostPaid', 'PostPaid', 'BPOS', 'BSNL', 'Prepaid', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/bsnl.webp', 1, NOW(), NOW()),
('PostPaid', 'PostPaid', 'RGPOS', 'Jio', 'Prepaid', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/jio1.png', 1, NOW(), NOW()),
('PostPaid', 'PostPaid', 'VIPOS', 'Vodafone Idea', 'Prepaid', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/vi1.png', 1, NOW(), NOW()),
('DTH', 'DTH', 'AD', 'Airtel Digital TV', 'DTH', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/airtel.png', 1, NOW(), NOW()),
('DTH', 'DTH', 'DT', 'Dish TV', 'DTH', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/dish-tv.png', 1, NOW(), NOW()),
('DTH', 'DTH', 'SD', 'Sun Direct', 'DTH', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/sun-direct.png', 1, NOW(), NOW()),
('DTH', 'DTH', 'TS', 'Tata Play', 'DTH', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/tata-play.png', 1, NOW(), NOW()),
('DTH', 'DTH', 'VT', 'Videocon d2h', 'DTH', 'Number', 'https://enexademo.in/nidhi/Uploads/OpratorImage/icons/d2h.png', 1, NOW(), NOW());