<?php
namespace App\Http\Controllers\CRM;

use App\Http\Controllers\Controller;
use App\Models\LeadActivity;
use Illuminate\Http\Request;

class LeadActivityController extends Controller
{
    /**
     * Display a listing of activities (Read-only)
     * Activities are now auto-generated by the system
     */
    public function index(Request $request) {
        $query = LeadActivity::with(['lead', 'user', 'createdBy']);

        if($request->get('isAdmin')) {
            $query->where('admin_id', $request->get('admin')->id);
        } else {
            $query->where('created_by', $request->get('user')->id);
        }

        // Filter by lead_id if provided
        if ($request->has('lead_id')) {
            $query->where('lead_id', $request->lead_id);
        }

        // Filter by activity type if provided
        if ($request->has('activity_type')) {
            $query->where('activity_type', $request->activity_type);
        }

        return $query->orderBy('created_at', 'desc')->get();
    }

    /**
     * Display the specified activity (Read-only)
     */
    public function show($id) { 
        return LeadActivity::with(['lead', 'user', 'createdBy'])->findOrFail($id); 
    }

    /**
     * Get activities for a specific lead
     */
    public function getByLead(Request $request, $leadId) {
        $activities = LeadActivity::with(['user', 'createdBy'])
            ->where('lead_id', $leadId)
            ->orderBy('created_at', 'desc')
            ->get();

        // Enhance activities with additional context
        $enhancedActivities = $activities->map(function($activity) {
            $data = $activity->toArray();
            
            // Add followup-related data if activity is followup_created
            if ($activity->activity_type === 'followup_created') {
                // Find the related followup
                $followup = \App\Models\Followup::with(['followupType', 'followupStatus'])
                    ->where('lead_id', $activity->lead_id)
                    ->where('created_at', '>=', $activity->created_at->subMinutes(5))
                    ->where('created_at', '<=', $activity->created_at->addMinutes(5))
                    ->first();
                
                if ($followup) {
                    $data['followup_type'] = $followup->followupType ? $followup->followupType->name : null;
                    $data['followup_type_id'] = $followup->followup_type_id;
                    $data['followup_type_color'] = $followup->followupType ? $followup->followupType->color : null;
                    $data['followup_status'] = $followup->followupStatus ? $followup->followupStatus->name : null;
                    $data['followup_status_id'] = $followup->followup_status_id;
                    $data['followup_status_color'] = $followup->followupStatus ? $followup->followupStatus->color : null;
                    $data['followup_time'] = $followup->followup_time ?? null;
                    $data['followup_notes'] = $followup->notes ?? null;
                    $data['lead_status_id'] = $followup->lead_status_id ?? null;
                }
            }
            
            // Add lead status information
            $lead = \App\Models\Lead::with('status')->find($activity->lead_id);
            if ($lead && $lead->status) {
                $data['lead_status'] = $lead->status->name;
                $data['lead_status_color'] = $lead->status->color;
            }
            
            return $data;
        });

        return response()->json(['activities' => $enhancedActivities]);
    }

    /**
     * Manual CRUD operations are disabled for activities
     * Activities are now automatically created by the system
     */
    public function store(Request $request) {
        return response()->json([
            'error' => 'Manual activity creation is disabled. Activities are automatically logged by the system.'
        ], 403);
    }

    public function update(Request $request, $id) {
        return response()->json([
            'error' => 'Manual activity editing is disabled. Activities are automatically managed by the system.'
        ], 403);
    }

    public function destroy(Request $request, $id) {
        return response()->json([
            'error' => 'Manual activity deletion is disabled. Activities are automatically managed by the system.'
        ], 403);
    }
}
